package edu.poly.common;

public enum PageType {
	//AAMIN
	USER_MANAGEMENT_PAGE,
	REPORT_MANAGEMRNT_PAGE,
	VIDEO_MANAGEMENT_PAGE,
	INDEX_PAGE,
	
	// User
	SITE_HOME_PAGE,
	SITE_LOGIN_PAGE,
	SITE_REGISTRATION_PAGE,
	
	SITE_CHANGEPASSWORD_PAGE,
	SITE_EDIT_PROFILE_PAGE,
	SITE_FORGOT_PASSWORD_PAGE,
	SITE_VIDEO_DETAIL_PAGE,
	SITE_FAVORITE_PAGE,
	SITE_SHARE_PAGE,
	SITE_DETAIL_PAGE,
	
	SITE_CONTACT_US_PAGE,
	SITE_ABOUT_US_PAGE
}
